### ISSUE TITLE
NOT work with v1.25.14-k3s1, the web UI keep loading... and onthing returned

### ISSUE THREAD

**Issue by gowy222** [niusmallnan/kube-explorer#36] opened 2023-09-22 10:30 UTC
E0922 10:27:55.959084      15 cacher.go:440] cacher (*flowcontrol.PriorityLevelConfiguration): unexpected ListAndWatch error: failed to list *flowcontrol.PriorityLevelConfiguration: no kind "PriorityLevelConfiguration" is registered for version "flowcontrol.apiserver.k8s.io/v1beta3" in scheme "k8s.io/apimachinery@v1.25.14-k3s1/pkg/runtime/scheme.go:100"; reinitializing...
W0922 10:27:56.043618      15 reflector.go:424] storage/cacher.go:/flowschemas: failed to list *flowcontrol.FlowSchema: no kind "FlowSchema" is registered for version "flowcontrol.apiserver.k8s.io/v1beta3" in scheme "k8s.io/apimachinery@v1.25.14-k3s1/pkg/runtime/scheme.go:100"
E0922 10:27:56.043651      15 cacher.go:440] cacher (*flowcontrol.FlowSchema): unexpected ListAndWatch error: failed to list *flowcontrol.FlowSchema: no kind "FlowSchema" is registered for version "flowcontrol.apiserver.k8s.io/v1beta3" in scheme "k8s.io/apimachinery@v1.25.14-k3s1/pkg/runtime/scheme.go:100"; reinitializing...
W0922 10:27:56.043892      15 reflector.go:424] storage/cacher.go:/flowschemas: failed to list *flowcontrol.FlowSchema: no kind "FlowSchema" is registered for version "flowcontrol.apiserver.k8s.io/v1beta3" in scheme "k8s.io/apimachinery@v1.25.14-k3s1/pkg/runtime/scheme.go:100"
E0922 10:27:56.043912      15 cacher.go:440] cacher (*flowcontrol.FlowSchema): unexpected ListAndWatch error: failed to list *flowcontrol.FlowSchema: no kind "FlowSchema" is registered for version "flowcontrol.apiserver.k8s.io/v1beta3" in scheme "k8s.io/apimachinery@v1.25.14-k3s1/pkg/runtime/scheme.go:100"; reinitializing...
W0922 10:27:56.044465      15 reflector.go:424] storage/cacher.go:/prioritylevelconfigurations: failed to list *flowcontrol.PriorityLevelConfiguration: no kind "PriorityLevelConfiguration" is registered for version "flowcontrol.apiserver.k8s.io/v1beta3" in scheme "k8s.io/apimachinery@v1.25.14-k3s1/pkg/runtime/scheme.go:100"
E0922 10:27:56.044490      15 cacher.go:440] cacher (*flowcontrol.PriorityLevelConfiguration): unexpected ListAndWatch error: failed to list *flowcontrol.PriorityLevelConfiguration: no kind "PriorityLevelConfiguration" is registered for version "flowcontrol.apiserver.k8s.io/v1beta3" in scheme "k8s.io/apimachinery@v1.25.14-k3s1/pkg/runtime/scheme.go:100"; reinitializing...

**Comment by orangedeng** [comment] 2023-11-10 08:07
It seems like it is the K8s API compatible issue. Please try to upgrade kube-explorer version.
I am not able to reproduce this issue with k3d v1.25.14-k3s1 and kube-explorer v0.3.4-rc1. Maybe you can share the kube-explorer version and the way you deploy your cluster and I will try to reproduce this issue.

**Comment by orangedeng** [comment] 2024-07-24 07:16
Closing this issue as it doesn't get reported again. Feel free to re-open this issue if needed.

**Closed as completed by orangedeng** 2024-07-24 07:16 UTC
