### ISSUE TITLE
Cannot "Execute Shell" nor " "View Log" on workload

### ISSUE THREAD

**Issue by ferry** [niusmallnan/kube-explorer#37] opened 2023-09-30 13:12 UTC
Hi,

I cannot connect to an container shell nor to it's logging. Errors I see:

```
62552 upgradeaware.go:369] Error proxying data from backend to client: write tcp [::1]:9443->[::1]:50821: write: broken pipe
```

See this on:
- k3s v1.22.15 and release v0.2.15
- k3s v1.26.7+k3s1 and release v0.3.3

**Comment by orangedeng** [comment] 2023-11-16 03:00
Hi, I can't reproduce your issue in this case `k3s v1.26.7+k3s1 and release v0.3.3`. Can you provide more informations like OS version and browser version?
I am using chrome version `119.0.6045.123(x86_64)` in macOS 13.5.2. The kube-explorer runs locally and the k3s is running on Ubuntu 22.03-LTS.

**Comment by ferry** [comment] 2023-11-17 13:07
Just tested k3s v1.26.7+k3s1 and release v0.3.3 and same result. k3s cluster runs on ubuntu 20.04. My kube-explorer runs on my macos 14.0 on m1 (arm) mackbook and have tested browsers microsoft edge beta and safari

edge error:
```
E1117 13:58:48.281357   95538 upgradeaware.go:396] Error proxying data from backend to client: write tcp [::1]:9443->[::1]:65358: write: broken pipe
```

safari errors:
```
INFO[0009] Watching metadata for autoscaling/v2, Kind=HorizontalPodAutoscaler
ERRO[0020] Error during subscribe websocket: close sent
ERRO[0020] Error during subscribe websocket: close sent
```

I am connecting through an openvpn tunnel though.

**Comment by orangedeng** [comment] 2024-07-24 07:16
Closing this issue as it doesn't get report again. Feel free to comment or re-open this issue if needed.

**Closed as completed by orangedeng** 2024-07-24 07:16 UTC

**Comment by ferry** [comment] 2024-11-11 14:52
v0.5 fixed this
